name: "Zeabur自动延长限期"

on:
  push:
    branches:
    - main
  schedule:
    - cron: '30 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
            python-version: '3.11'
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install selenium
      - name: 'Working'
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sudo cp -p ./chrome/chromedriver /usr/bin/
          chmod -R 777 /usr/bin/chromedriver
          python main.py